export const australiaStateList = [
  { id: 0, value: "Burgenland" },
  { id: 1, value: "Carinthia" },
  { id: 2, value: "Lower Austria" },
  { id: 3, value: "Salzburg" },
  { id: 4, value: "Styria" },
  { id: 5, value: "Tyrol" },
  { id: 6, value: "Upper Austria" },
  { id: 7, value: "Vienna" },
  { id: 8, value: "Vorarlberg" },
];
export const austriaStateList = [
  { id: 0, value: "New South Wales" },
  { id: 1, value: "Victoria" },
  { id: 2, value: "Queensland" },
  { id: 3, value: "Western Australia" },
  { id: 4, value: "South Australia" },
  { id: 5, value: "Tasmania" },
];
export const brazilStateList = [
  { id: 0, value: "Acre" },
  { id: 1, value: "Alagoas" },
  { id: 2, value: "Amapá" },
  { id: 3, value: "Amazonas" },
  { id: 4, value: "Bahia" },
  { id: 5, value: "Ceará" },
  { id: 6, value: "Distrito Federal" },
  { id: 7, value: "Espírito Santo" },
  { id: 8, value: "Goiás" },
  { id: 9, value: "Maranhão" },
  { id: 10, value: "Mato Grosso" },
  { id: 11, value: "Mato Grosso do Sul" },
  { id: 12, value: "Minas Gerais" },
  { id: 13, value: "Pará" },
  { id: 14, value: "Paraíba" },
  { id: 15, value: "Paraná" },
  { id: 16, value: "Pernambuco" },
  { id: 17, value: "Piauí" },
  { id: 18, value: "Rio de Janeiro" },
  { id: 19, value: "Rio Grande do Norte" },
  { id: 20, value: "Rio Grande do Sul" },
  { id: 21, value: "Rondônia" },
  { id: 22, value: "Roraima" },
  { id: 23, value: "Santa Catarina" },
  { id: 24, value: "São Paulo" },
  { id: 25, value: "Sergipe" },
  { id: 26, value: "Tocantins" },
];
export const germanyStateList = [
  { id: 0, value: "Baden-Württemberg" },
  { id: 1, value: "Bavaria (Bayern)" },
  { id: 2, value: "Berlin" },
  { id: 3, value: "Brandenburg" },
  { id: 4, value: "Bremen" },
  { id: 5, value: "Hamburg" },
  { id: 6, value: "Hesse (Hessen)" },
  { id: 7, value: "Lower Saxony (Niedersachsen)" },
  { id: 8, value: "Mecklenburg-Vorpommern" },
  { id: 9, value: "North Rhine-Westphalia (Nordrhein-Westfalen)" },
  { id: 10, value: "Rhineland-Palatinate (Rheinland-Pfalz)" },
  { id: 11, value: "Saarland" },
  { id: 12, value: "Saxony-Anhalt (Sachsen-Anhalt)" },
  { id: 13, value: "Saxony (Sachsen)" },
  { id: 14, value: "Schleswig-Holstein" },
  { id: 15, value: "Thuringia (Thüringen)" },
];
export const indiaStateList = [
  { id: 0, value: "Andhra Pradesh" },
  { id: 1, value: "Arunachal Pradesh" },
  { id: 2, value: "Assam" },
  { id: 3, value: "Bihar" },
  { id: 4, value: "Chhattisgarh" },
  { id: 5, value: "Goa" },
  { id: 6, value: "Gujarat" },
  { id: 7, value: "Haryana" },
  { id: 8, value: "Himachal Pradesh" },
  { id: 9, value: "Jharkhand" },
  { id: 10, value: "Karnataka" },
  { id: 11, value: "Kerala" },
  { id: 12, value: "Madhya Pradesh" },
  { id: 13, value: "Maharashtra" },
  { id: 14, value: "Manipur" },
  { id: 15, value: "Meghalaya" },
  { id: 16, value: "Mizoram" },
  { id: 17, value: "Nagaland" },
  { id: 18, value: "Odisha" },
  { id: 19, value: "Punjab" },
  { id: 20, value: "Rajasthan" },
  { id: 21, value: "Sikkim" },
  { id: 22, value: "Tamil Nadu" },
  { id: 23, value: "Telangana" },
  { id: 24, value: "Tripura" },
  { id: 25, value: "Uttar Pradesh" },
  { id: 26, value: "Uttarakhand" },
  { id: 27, value: "West Bengal" },
];
export const malaysiaStateList = [
  { id: 0, value: "Johor" },
  { id: 1, value: "Kedah" },
  { id: 2, value: "Kelantan" },
  { id: 3, value: "Malacca" },
  { id: 4, value: "Negeri Sembilan" },
  { id: 5, value: "Pahang" },
  { id: 6, value: "Penang" },
  { id: 7, value: "Perak" },
  { id: 8, value: "Perlis" },
  { id: 9, value: "Sabah" },
  { id: 10, value: "Sarawak" },
  { id: 11, value: "Selangor" },
  { id: 12, value: "Terengganu" },
];
export const mexicoStateList = [
  { id: 0, value: "Aguascalientes" },
  { id: 1, value: "Baja California" },
  { id: 2, value: "Baja California Sur" },
  { id: 3, value: "Campeche" },
  { id: 4, value: "Chiapas" },
  { id: 5, value: "Chihuahua" },
  { id: 6, value: "Coahuila[b][c]" },
  { id: 7, value: "Colima[d]" },
  { id: 8, value: "Durango" },
  { id: 9, value: "Guanajuato" },
  { id: 10, value: "Guerrero" },
  { id: 11, value: "Hidalgo" },
  { id: 12, value: "Jalisco" },
  { id: 13, value: "México" },
  { id: 14, value: "Mexico City[e]" },
  { id: 15, value: "Michoacán" },
  { id: 16, value: "Morelos" },
  { id: 17, value: "Nayarit" },
  { id: 18, value: "Nuevo León[c]" },
  { id: 19, value: "Oaxaca" },
  { id: 20, value: "Puebla" },
  { id: 21, value: "Querétaro" },
  { id: 22, value: "Quintana Roo" },
  { id: 23, value: "San Luis Potosí" },
  { id: 24, value: "Sinaloa" },
  { id: 25, value: "Sonora[f]" },
  { id: 26, value: "Tabasco[g]" },
  { id: 27, value: "Tamaulipas[c]" },
  { id: 28, value: "Tlaxcala" },
  { id: 29, value: "Veracruz" },
  { id: 30, value: "Yucatán[h]" },
  { id: 31, value: "Zacatecas" },
];
export const micronesiaStateList = [
  { id: 0, value: "Yap" },
  { id: 1, value: "Chuuk" },
  { id: 2, value: "Pohnpei" },
  { id: 3, value: "Kosrae" },
];
export const myanmarStateList = [
  { id: 0, value: "Ayeyarwady Region" },
  { id: 1, value: "Bago Region" },
  { id: 2, value: "Chin State" },
  { id: 3, value: "Kachin State" },
  { id: 4, value: "Kayah State" },
  { id: 5, value: "Kayin State" },
  { id: 6, value: "Magway Region" },
  { id: 7, value: "Mandalay Region" },
  { id: 8, value: "Mon State" },
  { id: 9, value: "Rakhine State" },
  { id: 10, value: "Sagaing Region" },
  { id: 11, value: "Shan State" },
  { id: 12, value: "Tanintharyi Region" },
  { id: 13, value: "Yangon Region" },
];
export const newZealandStateList = [
  { id: 0, value: "Auckland" },
  { id: 1, value: "Canterbury" },
  { id: 2, value: "Wellington" },
  { id: 3, value: "Waikato" },
  { id: 4, value: "Bay of Plenty" },
  { id: 5, value: "Manawatu-Wanganui" },
  { id: 6, value: "Otago" },
  { id: 7, value: "Hawkes Bay" },
  { id: 8, value: "Northland" },
  { id: 9, value: "Taranaki" },
  { id: 10, value: "Southland" },
  { id: 11, value: "Nelson" },
  { id: 12, value: "Gisborne" },
  { id: 13, value: "Marlborough" },
  { id: 14, value: "Tasman" },
  { id: 15, value: "West Coast" },
];
export const nigeriaStateList = [
  { id: 0, value: "Niger State" },
  { id: 1, value: "Borno State" },
  { id: 2, value: "Taraba State" },
  { id: 3, value: "Kaduna State" },
  { id: 4, value: "Bauchi State" },
  { id: 5, value: "Yobe State" },
  { id: 6, value: "Zamfara State" },
  { id: 7, value: "Adamawa State" },
  { id: 8, value: "Kwara State" },
  { id: 9, value: "Kebbi State" },
  { id: 10, value: "Benue State" },
  { id: 11, value: "Plateau State" },
  { id: 12, value: "Kogi State" },
  { id: 13, value: "Oyo State" },
  { id: 14, value: "Nasarawa State" },
  { id: 15, value: "Sokoto State" },
  { id: 16, value: "Katsina State" },
  { id: 17, value: "Jigawa State" },
  { id: 18, value: "Cross River State" },
  { id: 19, value: "Kano State" },
  { id: 20, value: "Gombe State" },
  { id: 21, value: "Edo State" },
  { id: 22, value: "Delta State" },
  { id: 23, value: "Ogun State" },
  { id: 24, value: "Ondo State" },
  { id: 25, value: "Rivers State" },
  { id: 26, value: "Bayelsa State" },
  { id: 27, value: "Osun State" },
  { id: 28, value: "Enugu State" },
  { id: 29, value: "Akwa Ibom State" },
  { id: 30, value: "Ekiti State" },
  { id: 31, value: "Abia State" },
  { id: 32, value: "Ebonyi State" },
  { id: 33, value: "Imo State" },
  { id: 34, value: "Anambra State" },
  { id: 35, value: "Lagos State" },
];
export const palauStateList = [
  { id: 0, value: "Kayangel" },
  { id: 1, value: "Aimeliik" },
  { id: 2, value: "Airai" },
  { id: 3, value: "Melekeok" },
  { id: 4, value: "Ngaraard" },
  { id: 5, value: "Ngarchelong" },
  { id: 6, value: "Ngardmau" },
  { id: 7, value: "Ngeremlengui" },
  { id: 8, value: "Ngatpang" },
  { id: 9, value: "Ngchesar" },
  { id: 10, value: "Ngiwal" },
  { id: 11, value: "Angaur" },
  { id: 12, value: "Koror" },
  { id: 13, value: "Peleliu" },
  { id: 14, value: "Hatohobei" },
  { id: 15, value: "Sonsorol" },
];
export const southSudanStateList = [
  { id: 0, value: "Akobo State" },
  { id: 1, value: "Bieh State" },
  { id: 2, value: "Boma State" },
  { id: 3, value: "Fangak State" },
  { id: 4, value: "Jonglei State" },
  { id: 5, value: "Northern Liech State" },
  { id: 6, value: "Ruweng State" },
  { id: 7, value: "Southern Liech State" },
  { id: 8, value: "Central Upper Nile State" },
  { id: 9, value: "Fashoda State" },
  { id: 10, value: "Latjor State" },
  { id: 11, value: "Maiwut State" },
  { id: 12, value: "Northern Upper Nile State" },
  { id: 13, value: "Eastern Lakes State" },
  { id: 14, value: "Gok State" },
  { id: 15, value: "Western Lakes State" },
  { id: 16, value: "Aweil East State" },
  { id: 17, value: "Aweil State" },
  { id: 18, value: "Gogrial State" },
  { id: 19, value: "Tonj State" },
  { id: 20, value: "Twic State" },
  { id: 21, value: "Lol State" },
  { id: 22, value: "Wau State" },
  { id: 23, value: "Jubek State" },
  { id: 24, value: "Terekeka State" },
  { id: 25, value: "Yei River State" },
  { id: 26, value: "Imatong State" },
  { id: 27, value: "Kapoeta State" },
  { id: 28, value: "Amadi State" },
  { id: 29, value: "Gbudwe State" },
  { id: 30, value: "Maridi State" },
  { id: 31, value: "Tambura State" },
];
export const usStateList = [
  { id: 0, value: "Alabama" },
  { id: 1, value: "Alaska" },
  { id: 2, value: "Arizona" },
  { id: 3, value: "Arkansas" },
  { id: 4, value: "California" },
  { id: 5, value: "Colorado" },
  { id: 6, value: "Connecticut" },
  { id: 7, value: "Delaware" },
  { id: 8, value: "Florida" },
  { id: 9, value: "Georgia" },
  { id: 10, value: "Hawaii" },
  { id: 11, value: "Idaho" },
  { id: 12, value: "Illinois" },
  { id: 13, value: "Indiana" },
  { id: 14, value: "Iowa" },
  { id: 15, value: "Kansas" },
  { id: 16, value: "Kentucky[D]" },
  { id: 17, value: "Louisiana" },
  { id: 18, value: "Maine" },
  { id: 19, value: "Maryland" },
  { id: 20, value: "Massachusetts[D]" },
  { id: 21, value: "Michigan" },
  { id: 22, value: "Minnesota" },
  { id: 23, value: "Mississippi" },
  { id: 24, value: "Missouri" },
  { id: 25, value: "Montana" },
  { id: 26, value: "Nebraska" },
  { id: 27, value: "Nevada" },
  { id: 28, value: "New Hampshire" },
  { id: 29, value: "New Jersey" },
  { id: 30, value: "New Mexico" },
  { id: 31, value: "New York" },
  { id: 32, value: "North Carolina" },
  { id: 33, value: "North Dakota" },
  { id: 34, value: "Ohio" },
  { id: 35, value: "Oklahoma" },
  { id: 36, value: "Oregon" },
  { id: 37, value: "Pennsylvania[D]" },
  { id: 38, value: "Rhode Island" },
  { id: 39, value: "South Carolina" },
  { id: 40, value: "South Dakota" },
  { id: 41, value: "Tennessee" },
  { id: 42, value: "Texas" },
  { id: 43, value: "Utah" },
  { id: 44, value: "Vermont" },
  { id: 45, value: "Virginia[D]" },
  { id: 46, value: "Washington" },
  { id: 47, value: "West Virginia" },
  { id: 48, value: "Wisconsin" },
  { id: 49, value: "Wyoming" },
];
